"""add_github_token_fields

Revision ID: 5ca99d237685
Revises: 69153e2bd29c
Create Date: 2026-01-14 23:15:49.982104+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ca99d237685'
down_revision: Union[str, None] = '69153e2bd29c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('knowledge_entries', sa.Column('context_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    op.add_column('users', sa.Column('github_access_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('github_token_expires', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('github_username', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'github_username')
    op.drop_column('users', 'github_token_expires')
    op.drop_column('users', 'github_access_token')
    op.drop_column('knowledge_entries', 'context_embedding')
    # ### end Alembic commands ###
